language: lua

script:
        - cd test
        - sudo apt install -y lua5.3
        - lua5.3 *.lua -v

notifications:
        email:
                on_success: change
                on_failure: always
